### ISSUE TITLE
可以出一个vercel版本的吗

### ISSUE THREAD

**Issue by izoro-y** [QJune/wx_lovers#2]
就是vercel是一个可以部署项目的网站 可以出一个在vercel部署的版本吗

**Comment by Qiu-Jun** [comment]
刚看了一下vercel好像可以部署服务，我有空去看看

**Comment by x-dr** [comment]
vercel不行吧，heroku可以试试

**Comment by Qiu-Jun** [comment]
> vercel不行吧，heroku可以试试


看了下heroku，确实灵活但是免费的有点差了。vercel我尝试了一下用koa时通了，没有深入研究

**Comment by lixinzai** [comment]
> > vercel不行吧，heroku可以试试
> 
> 看了下heroku，确实灵活但是免费的有点差了。vercel我尝试了一下用koa时通了，没有深入研究

直接打包docker应该比heroku方便

**Comment by QJune** [comment]
> 

他们主要是要云平台部署- -

**Comment by Qiu-Jun** [comment]
> > > vercel不行吧，heroku可以试试
> > 
> > 
> > 看了下heroku，确实灵活但是免费的有点差了。vercel我尝试了一下用koa时通了，没有深入研究
> 
> 直接打包docker应该比heroku方便

他们主要是要云平台部署- -

**Comment by Qiu-Jun** [comment]
你好，由于我这边没时间，不去搞vercel版本了。大概给你个思路，你自己去研究研究咯。由于vercel不支持缓存，由于微信那个access_token有次数限制，不过如果只做每日推送的话，可以忽略。使用前调微信接口换access_token，然后再调微信发推送消息的接口(处理好参数就可以了)，最后通过git Actions做定时
